# Setup
title:               Alexander Hoffman
tagline:             'Computational heterogeneous catalysis and materials engineering research'
description:         ""
url:                 http://ajhoffman1229.github.io
baseurl:             /
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Alexander Hoffman
  url:               https://twitter.com/ajhoffman1229
  email:             ""

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
